# -*- mode: python ; coding: utf-8 -*-

import sys
from pathlib import Path

block_cipher = None

a = Analysis(
    ['webui.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
        ('src', 'src'),
    ],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.loops.asyncio',
        'uvicorn.loops.uvloop',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.http.httptools_impl',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.protocols.websockets.websockets_impl',
        'uvicorn.protocols.websockets.wsproto_impl',
        'uvicorn.lifespan',
        'uvicorn.lifespan.off',
        'uvicorn.lifespan.on',
        'fastapi',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'fastapi.staticfiles',
        'fastapi.templating',
        'starlette',
        'starlette.routing',
        'starlette.middleware',
        'starlette.staticfiles',
        'starlette.templating',
        'jinja2',
        'sqlalchemy',
        'sqlalchemy.orm',
        'sqlalchemy.orm.session',
        'sqlalchemy.orm.decl_api',
        'sqlalchemy.ext.declarative',
        'sqlalchemy.engine',
        'sqlalchemy.engine.create',
        'sqlalchemy.engine.url',
        'sqlalchemy.pool',
        'sqlalchemy.sql',
        'sqlalchemy.sql.schema',
        'sqlalchemy.sql.sqltypes',
        'sqlalchemy.dialects',
        'sqlalchemy.dialects.sqlite',
        'sqlalchemy.dialects.sqlite.pysqlite',
        'aiosqlite',
        'pydantic',
        'pydantic_settings',
        'curl_cffi',
        'curl_cffi.requests',
        'email.mime',
        'email.mime.text',
        'email.mime.multipart',
        'imaplib',
        'h11',
        'anyio',
        'anyio.lowlevel',
        'click',
        'src.web.app',
        'src.web.routes',
        'src.config.settings',
        'src.config.constants',
        'src.database.models',
        'src.database.session',
        'src.database.crud',
        'src.database.init_db',
        'src.core.register',
        'src.core.http_client',
        'src.core.utils',
        'src.services.base',
        'src.services.tempmail',
        'src.services.yyds_mail',
        'src.services.moe_mail',
        'src.services.outlook',
        'src.services.outlook.account',
        'src.services.outlook.base',
        'src.services.outlook.email_parser',
        'src.services.outlook.health_checker',
        'src.services.outlook.service',
        'src.services.outlook.token_manager',
        'src.services.outlook.providers',
        'src.services.outlook.providers.base',
        'src.services.outlook.providers.graph_api',
        'src.services.outlook.providers.imap_new',
        'src.services.outlook.providers.imap_old',
        'src.services.outlook_legacy_mail',
        'src.core.openai.oauth',
        'src.core.openai.token_refresh',
        'src.core.upload.cpa_upload',
        'src.core.upload.sub2api_upload',
        'src.core.upload.team_manager_upload',
        'src.web.routes.accounts',
        'src.web.routes.email',
        'src.web.routes.registration',
        'src.web.routes.settings',
        'src.web.routes.websocket',
        'src.web.task_manager',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'PIL',
        'pytest',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='codex-console',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
